# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:15 # 使用官方的PostgreSQL 15版本镜像
    restart: always
    environment:
      POSTGRES_USER: user # 数据库用户名
      POSTGRES_PASSWORD: password # 数据库密码
      POSTGRES_DB: baking-saas # 数据库名称
    ports:
      - '5432:5432' # 将电脑的5432端口映射到容器的5432端口
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
